# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cases',
        ),
    ]
