# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200611_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(choices=[('singles', 'singles'), ('mixed_cases', 'mixed_cases'), ('merchandise', 'merchandise')], default='singles', max_length=120, to='products.Category'),
        ),
    ]
