# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-11 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200611_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='name',
        ),
    ]
