# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-11 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200611_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('singles', 'singles'), ('mixed_cases', 'mixed_cases'), ('merchandise', 'merchandise')], default='singles', max_length=120),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
